mutation PATCH_MDFIELDS($acronym: String!, $document: DocumentInput, $account: String) {
	updateDocument(acronym: $acronym, document: $document, account: $account) {
		cacheId
		id
		href
		documentId
	}
}

# {
#   "acronym": "CL",
#   "account": "gigadigital",
#   "document":
#       {
#         "fields": [
#           {
#             "key": "isWhatsappOptIn",
#             "value": "true"
#           },
#           {
#             "key": "id",
#             "value": "3fec9561-5760-11eb-82ac-02bfcd685167" session
#           }
#         ]
#       }

# }
