query GET_FIXED_PRICES($itemID: Int) {
  fixedPrices(itemID: $itemID) {
    itemId
    listPrice
    costPrice
    markup
    basePrice
    fixedPrices {
      tradePolicyId
      value
      listPrice
      minQuantity
    }
  }
}
